package com.community.cyd.mapper;

import com.community.cyd.model.Consult;
import com.community.cyd.model.ConsultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConsultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    long countByExample(ConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int deleteByExample(ConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int insert(Consult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int insertSelective(Consult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    List<Consult> selectByExampleWithRowbounds(ConsultExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    List<Consult> selectByExample(ConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    Consult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Consult record, @Param("example") ConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int updateByExample(@Param("record") Consult record, @Param("example") ConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int updateByPrimaryKeySelective(Consult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSULT
     *
     * @mbg.generated Fri May 15 10:56:53 CST 2020
     */
    int updateByPrimaryKey(Consult record);
}