package com.community.cyd.model;

public class Consult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSULT.ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSULT.CONSULTEE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private Long consultee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSULT.CONSULTANT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private Long consultant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSULT.CONTENT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSULT.FEE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private String fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSULT.GMT_CREATE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSULT.ID
     *
     * @return the value of CONSULT.ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSULT.ID
     *
     * @param id the value for CONSULT.ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSULT.CONSULTEE
     *
     * @return the value of CONSULT.CONSULTEE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public Long getConsultee() {
        return consultee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSULT.CONSULTEE
     *
     * @param consultee the value for CONSULT.CONSULTEE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setConsultee(Long consultee) {
        this.consultee = consultee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSULT.CONSULTANT
     *
     * @return the value of CONSULT.CONSULTANT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public Long getConsultant() {
        return consultant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSULT.CONSULTANT
     *
     * @param consultant the value for CONSULT.CONSULTANT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setConsultant(Long consultant) {
        this.consultant = consultant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSULT.CONTENT
     *
     * @return the value of CONSULT.CONTENT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSULT.CONTENT
     *
     * @param content the value for CONSULT.CONTENT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSULT.FEE
     *
     * @return the value of CONSULT.FEE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSULT.FEE
     *
     * @param fee the value for CONSULT.FEE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSULT.GMT_CREATE
     *
     * @return the value of CONSULT.GMT_CREATE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSULT.GMT_CREATE
     *
     * @param gmtCreate the value for CONSULT.GMT_CREATE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}