package com.community.cyd.model;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAYMENT.ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAYMENT.USER_ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAYMENT.OUT_TRADE_NO
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAYMENT.TRADE_NO
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAYMENT.TOTAL_AMOUNT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private String totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAYMENT.GMT_CREATE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAYMENT.ID
     *
     * @return the value of PAYMENT.ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAYMENT.ID
     *
     * @param id the value for PAYMENT.ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAYMENT.USER_ID
     *
     * @return the value of PAYMENT.USER_ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAYMENT.USER_ID
     *
     * @param userId the value for PAYMENT.USER_ID
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAYMENT.OUT_TRADE_NO
     *
     * @return the value of PAYMENT.OUT_TRADE_NO
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAYMENT.OUT_TRADE_NO
     *
     * @param outTradeNo the value for PAYMENT.OUT_TRADE_NO
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAYMENT.TRADE_NO
     *
     * @return the value of PAYMENT.TRADE_NO
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAYMENT.TRADE_NO
     *
     * @param tradeNo the value for PAYMENT.TRADE_NO
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAYMENT.TOTAL_AMOUNT
     *
     * @return the value of PAYMENT.TOTAL_AMOUNT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAYMENT.TOTAL_AMOUNT
     *
     * @param totalAmount the value for PAYMENT.TOTAL_AMOUNT
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount == null ? null : totalAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAYMENT.GMT_CREATE
     *
     * @return the value of PAYMENT.GMT_CREATE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAYMENT.GMT_CREATE
     *
     * @param gmtCreate the value for PAYMENT.GMT_CREATE
     *
     * @mbg.generated Thu May 14 00:48:49 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}