CREATE TABLE USER(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    ACCOUNT_ID VARCHAR(100),
    NAME VARCHAR(50),
    TOKEN CHAR,
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    AVATAR_URL varchar(200)
);